spring:
  cloud:
    nacos:
      discovery:
        server-addr: jd.itnxd.cn:8848
    alicloud:
      access-key:
      secret-key:
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-nxd
  application:
    name: gulimall-third-party

server:
  port: 30000